### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by sschuberth**

### CODE REVIEW

**Review by Etsija — CHANGES_REQUESTED** [review]
I would leave this commit out from the PR, as I'm already working on a proper fix to tests.  I've taken some of the fixes in this commit to my local fix branch.

**Comment by sschuberth** [comment]
> as I'm already working on a proper fix to tests.

Mind elaborating what's "improper" about the test changes in this PR? Just curious.

It's really just mostly fixups to wrong adoptions done by myself in fe81c29384ebeb8439ffee4ecdb71bf56bd17049, e.g. `"purl"` should not have been replaced by `emptyList()` in the first place, but with `listOf("purl")`.

**Comment by Etsija** [comment]
The test "scanPackage() should abort and log an issue when backend fails" should log the expected message, but doesn't, so the expected message shouldn't be changed.  Rather, I need to investigate and fix why the backend returns a wrong message.  I already have a hunch about that.

**Comment by sschuberth** [comment]
> The test "scanPackage() should abort and log an issue when backend fails" should log the expected message, but doesn't

Are you *sure* that new expected message from the PR isn't the actually correct one? Because previously

    "Could not get a presigned URL for this package"

was expected, which is the same message as expected for the

    "runBackendScan() with failing presigned URL retrieval should abort and log an issue"

test. To me, it makes sense that the

    "scanPackage() should abort and log an issue when backend fails"

test expects a different error message, esp one that do snot include the word "presigned", as the test name doesn't either.

**Comment by Etsija** [comment]
This'd be better taken up in daily or after that, I can explain it better.

**Comment by sschuberth** [comment]
@Etsija, I've incorporated your changes from the `fix-unit-tests` changes, broken up into smaller commits with respective messages each. Please have another look.

**Review by Etsija — APPROVED** [review]

**Pull request merged**
