### PR TITLE
Prepare for handling multiple PURLs per ZIP archive

### PR DESCRIPTION
**Pull request by sschuberth**
Please have a look at the individual commit messages for the details.

### CODE REVIEW

**Review by Etsija — COMMENTED** [review]
I don't know if the backend scan should be successful for non-monorepo case yet at this point or not, just a note that it isn't: tried it with mime-types (for which I deleted mime-types and left mime-db package at backend).  Creating the scanner job was unsuccessful, even it to my understanding should have been OK, with the call signature

`val jobResponse = repository.postScanJob(zipName, purls.first())`

**Comment by lamppu** [comment]
It failed because now the request was made with purl pkg:npm/mime-types@2.1.18# and since the path was empty, the computed purl now didn't have the # in the end. And I did realize earlier that the subpath shouldn't actually be saved in the database at all anyway, so I will have to parse it away. Or alternatively the request could actually be made with a list of objects that have a purl and a path.

**Comment by sschuberth** [comment]
> I don't know if the backend scan should be successful for non-monorepo case yet at this point or not

I actually should. I've tried to implement what you suggested, and prepare for the the client / backend code to be multi-PURL ready, without breaking existing functionality.

> Creating the scanner job was unsuccessful, even if it to my understanding should have been OK, with the call signature

Exactly, it should have worked. Can you be a more specific than "unsuccessful"?

**Comment by Etsija** [comment]
13:05:39.215 [main] INFO  org.ossreviewtoolkit.plugins.scanners.dos.DOS - Initiating a backend scan
13:05:39.228 [main] INFO  org.ossreviewtoolkit.clients.dos.DOSService - Directory /tmp/ort-BlockingCoroutine4976008996093787221 deleted
13:05:39.412 [main] INFO  org.ossreviewtoolkit.clients.dos.DOSService - Presigned URL from API successfully fetched
13:05:39.413 [main] INFO  org.ossreviewtoolkit.clients.dos.DOSService - Uploading file /tmp/ort-BlockingCoroutine4976008996093787221.zip of size 59 kB to S3
13:05:39.747 [main] INFO  org.ossreviewtoolkit.clients.dos.DOSService - Packet successfully uploaded to S3
13:05:39.748 [main] INFO  org.ossreviewtoolkit.clients.dos.DOSService - File /tmp/ort-BlockingCoroutine4976008996093787221.zip deleted
13:05:39.869 [main] ERROR org.ossreviewtoolkit.clients.dos.DOSService - Response{protocol=http/1.1, code=500, message=Internal Server Error, url=https://app-28ea69c2-39bc-4f55-a7e8-5cab18fedc35.cleverapps.io/api/job}
13:05:39.871 [main] ERROR java.lang.Object - Could not create a new scan job at DOS API
13:05:39.871 [main] ERROR kotlinx.coroutines.CoroutineScope - Something went wrong at DOS backend, exiting scan of this package

**Comment by sschuberth** [comment]
> It failed because now the request was made with purl pkg:npm/mime-types@2.1.18# and since the path was empty

Good point, I've fixed that now. I guess that should also fix @Etsija's test.

**Comment by Etsija** [comment]
After your force-pushed commit, it now works (for this non-monorepo case), so OK!

**Review by lamppu — APPROVED** [review]

**Comment by Etsija** [comment]
Do you have something else to put in this PR, or can it be merged, and maybe write a further PR later, to pick up possible loose ends, fix bugs etc?  I'd like to get this code on main, as I have a PR of my own in mind, and I'd like to base it on newest code.

**Comment by sschuberth** [comment]
> Do you have something else to put in this PR, or can it be merged

I'll merged it!

**Pull request merged**
